# Generated by Django 5.2.1 on 2025-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланировано'), ('completed', 'Завершено')], default='planned', max_length=20, verbose_name='Статус'),
        ),
    ]
