# Generated by Django 5.2.1 on 2025-05-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_trip_options_remove_trip_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
