# Generated by Django 5.2.1 on 2025-05-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_tags_trip_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='tags',
        ),
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.CharField(blank=True, max_length=200, verbose_name='Теги'),
        ),
    ]
