# Generated by Django 5.2.1 on 2025-05-25 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_trip_tags_trip_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='TripPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('point_type', models.CharField(choices=[('start', 'Начальная'), ('intermediate', 'Промежуточная'), ('end', 'Конечная')], default='intermediate', max_length=20, verbose_name='Тип точки')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_point_images/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='trips.trip', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Точка маршрута',
                'verbose_name_plural': 'Точки маршрута',
            },
        ),
    ]
