# Generated by Django 5.2.1 on 2025-05-25 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_alter_trip_date_trippoint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trippoint',
            options={'verbose_name': 'Точка маршрута', 'verbose_name_plural': 'Точки маршрутов'},
        ),
        migrations.RemoveField(
            model_name='trippoint',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trip_points/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название точки'),
        ),
        migrations.AlterField(
            model_name='trippoint',
            name='point_type',
            field=models.CharField(choices=[('start', 'Начало'), ('intermediate', 'Промежуточная точка'), ('end', 'Конец')], default='intermediate', max_length=20, verbose_name='Тип точки'),
        ),
    ]
